# Force include missing modules in initramfs (I2C, LPSS, Pin control) 
add_drivers+=" i2c_hid_acpi i2c_hid_of intel_lpss_pci intel_lpss_acpi pinctrl_amd pinctrl_intel psmouse "

# Fix for Plymouth with Keychron / Apple USB keyboards on CachyOS
add_drivers+=" hid-apple mac_hid "

# Ensure generic USB HID modules are included if they happen to be modules
add_drivers+=" hid-generic usbhid "
