# Force include missing modules in initramfs (I2C, LPSS, Pin control) 
add_drivers+=" i2c_hid_acpi i2c_hid_of intel_lpss_pci intel_lpss_acpi pinctrl_amd pinctrl_intel psmouse "

# Fix for Plymouth with Keychron / Apple USB keyboards on CachyOS
# Use force_drivers to load them early before udev and Plymouth to prevent unbind/rebind
force_drivers+=" hid-apple mac_hid "

