# Force l'inclusion des dépendances orphelines (I2C, LPSS, Pin control) 
# ignorées par dracut car les drivers HID/USB principaux sont maintenant built-in (CachyOS)
add_drivers+=" i2c_hid_acpi i2c_hid_of intel_lpss_pci intel_lpss_acpi pinctrl_amd pinctrl_intel psmouse "