#!/bin/bash
# Wrapper to redirect pkexec calls to systemd's run0

declare -a RUN0_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --user)
            RUN0_ARGS+=("--user=$2")
            shift 2
            ;;
        --user=*)
            RUN0_ARGS+=("--user=${1#--user=}")
            shift
            ;;
        --disable-internal-agent)
            # No direct equivalent in run0, safely ignored
            shift
            ;;
        --help)
            RUN0_ARGS+=("--help")
            shift
            ;;
        --version)
            RUN0_ARGS+=("--version")
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            RUN0_ARGS+=("$1")
            shift
            ;;
        *)
            break
            ;;
    esac
done

exec run0 "${RUN0_ARGS[@]}" "$@"
